import { defineSimulation } from '@/engine'
import { createInitialState, isComplete, measure, step } from './model'

/** Exported so the detector drag uses the same limits as the control. */
export const detectorVariable = {
  kind: 'number',
  id: 'detectorPosition',
  label: 'Detector position',
  description:
    'Where the light meter sits on the screen, measured from the centre. Drag it on the screen too.',
  unit: 'mm',
  defaultValue: 0,
  min: -15,
  max: 15,
  step: 0.01,
} as const

export const doubleSlit = defineSimulation({
  id: 'double-slit',
  domain: 'physics',
  title: 'Double Slit (YDSE)',
  description: 'Shine light through two narrow slits and see why bright and dark fringes form on the screen.',
  learningObjectives: [
    'Explain bright and dark fringes using path difference: bright where Δ = nλ, dark where Δ = (n + ½)λ.',
    'Use β = λD/d to predict how the fringe width changes with wavelength, slit separation and screen distance, and check it by measuring.',
    'Describe how the pattern changes when the apparatus is in water, or when one slit is dimmer than the other.',
  ],
  assumptions: [
    'The light is monochromatic and coherent (a laser), and both slits are lit in phase.',
    'The slits are very narrow, so the single-slit diffraction envelope is ignored and all bright fringes are equally bright. In a real experiment they fade away from the centre.',
    'Intensities are relative to I₀, the intensity one slit alone gives at the screen; the small fall-off across the screen is ignored.',
    'Fringe width uses β = λD/d (D ≫ d, small angles). Intensity uses the exact path difference; within ±15 mm the two agree to better than 0.01 %.',
    'The medium fills the whole apparatus: λ in the medium = λ/n, with n(air) ≈ 1.00 and n(water) = 1.33.',
    'Not to scale: distances along the bench are shortened and the slit separation is drawn larger.',
    'The sideways direction of the interference map and the screen is magnified about 133× so the fringes can be seen.',
    'The ripples from each slit are drawn with the wavelength hugely enlarged, and light is shown in extreme slow motion (real light crosses the bench in about 10 ns). The bright and dark bands, and the screen, use the true path difference.',
    'Colours approximate how each wavelength looks.',
  ],
  // From behind and above the laser, looking down the bench at the screen's face.
  scene: { worldUnit: '1', camera: { position: [-6.2, 6.4, 4.6], target: [3.4, -0.3, 0], fov: 45 } },
  variables: [
    {
      kind: 'number',
      id: 'wavelength',
      label: 'Wavelength λ',
      description: 'The colour of the laser light: violet ≈ 400 nm, green ≈ 530 nm, red ≈ 650 nm.',
      unit: 'nm',
      defaultValue: 600,
      min: 380,
      max: 750,
      step: 1,
    },
    {
      kind: 'number',
      id: 'slitSeparation',
      label: 'Slit separation d',
      description: 'Distance between the centres of the two slits.',
      unit: 'mm',
      defaultValue: 0.5,
      min: 0.1,
      max: 2,
      step: 0.01,
    },
    {
      kind: 'number',
      id: 'screenDistance',
      label: 'Screen distance D',
      description: 'Distance from the slits to the screen.',
      unit: 'm',
      defaultValue: 1.5,
      min: 1,
      max: 3,
      step: 0.05,
    },
    {
      kind: 'number',
      id: 'sourceIntensity',
      label: 'Source brightness',
      description: 'How bright the laser is. It changes how bright the fringes are, not where they are.',
      unit: '1',
      defaultValue: 1,
      min: 0.2,
      max: 1,
      step: 0.05,
    },
    {
      kind: 'number',
      id: 'slit2Intensity',
      label: 'Slit 2 brightness',
      description: 'Partly cover slit 2: 1 means both slits let through the same light.',
      unit: '1',
      defaultValue: 1,
      min: 0.1,
      max: 1,
      step: 0.05,
    },
    {
      kind: 'choice',
      id: 'medium',
      label: 'Medium',
      description: 'What fills the apparatus between the slits and the screen.',
      defaultValue: 'air',
      options: [
        { value: 'air', label: 'Air (n = 1.00)' },
        { value: 'water', label: 'Water (n = 1.33)' },
      ],
    },
    detectorVariable,
  ],
  // All conditions are steady: the pattern responds immediately, like moving a real screen.
  liveVariables: [
    'wavelength',
    'slitSeparation',
    'screenDistance',
    'sourceIntensity',
    'slit2Intensity',
    'medium',
    'detectorPosition',
  ],
  measurements: [
    {
      kind: 'scalar',
      id: 'fringeWidth',
      label: 'Fringe width β',
      description: 'Distance between neighbouring bright fringes: β = λD/d.',
      unit: 'mm',
      emphasis: 'primary',
    },
    {
      kind: 'scalar',
      id: 'detectorIntensity',
      label: 'Intensity at detector (I/I₀)',
      description: 'Brightness at the detector, compared with one slit alone.',
      unit: '1',
      emphasis: 'primary',
    },
    {
      kind: 'category',
      id: 'detectorFringe',
      label: 'At detector',
      description: 'Whether the detector sits on a bright fringe, a dark fringe or in between.',
      emphasis: 'primary',
      options: [
        { value: 'none', label: 'No light yet' },
        { value: 'bright', label: 'Bright fringe' },
        { value: 'dark', label: 'Dark fringe' },
        { value: 'between', label: 'Between fringes' },
      ],
    },
    { kind: 'scalar', id: 'pathDifference', label: 'Path difference Δ at detector', unit: 'nm' },
    { kind: 'scalar', id: 'fringeOrder', label: 'Δ ÷ λ at detector', unit: '1' },
    { kind: 'scalar', id: 'phaseDifference', label: 'Phase difference φ', unit: 'rad' },
    { kind: 'scalar', id: 'wavelengthInMedium', label: 'Wavelength in medium λₘ', unit: 'nm' },
    { kind: 'scalar', id: 'angularFringeWidth', label: 'Angular fringe width θ = λ/d', unit: 'rad' },
    { kind: 'scalar', id: 'maxIntensity', label: 'Brightest (I_max/I₀)', unit: '1' },
    { kind: 'scalar', id: 'minIntensity', label: 'Darkest (I_min/I₀)', unit: '1' },
    { kind: 'scalar', id: 'visibility', label: 'Fringe visibility', unit: '1' },
    { kind: 'scalar', id: 'brightFringesOnScreen', label: 'Bright fringes on screen', unit: '1' },
    {
      kind: 'category',
      id: 'phase',
      label: 'Light',
      options: [
        { value: 'off', label: 'Off' },
        { value: 'travelling', label: 'Travelling' },
        { value: 'formed', label: 'Pattern formed' },
      ],
    },
  ],
  objects: [
    { id: 'laser', label: 'Laser', selectable: true },
    { id: 'slits', label: 'Double slit', selectable: true },
    { id: 'screen', label: 'Screen', selectable: true },
    { id: 'detector', label: 'Detector', selectable: true },
  ],
  interactions: [
    { id: 'select-laser', kind: 'select', targetObjectId: 'laser' },
    { id: 'select-slits', kind: 'select', targetObjectId: 'slits' },
    { id: 'select-screen', kind: 'select', targetObjectId: 'screen' },
    { id: 'move-detector', kind: 'drag', targetObjectId: 'detector', variableId: 'detectorPosition' },
  ],
  presets: [
    { id: 'red', title: 'Red laser (650 nm)', variables: { wavelength: 650 } },
    { id: 'green', title: 'Green laser (532 nm)', variables: { wavelength: 532 } },
    { id: 'violet', title: 'Violet laser (405 nm)', variables: { wavelength: 405 } },
    { id: 'close-slits', title: 'Slits 0.25 mm apart', variables: { slitSeparation: 0.25 } },
    { id: 'far-screen', title: 'Screen at 3 m', variables: { screenDistance: 3 } },
    { id: 'water', title: 'In water', variables: { medium: 'water' } },
    { id: 'unequal', title: 'Slit 2 dimmed', variables: { slit2Intensity: 0.25 } },
  ],
  investigations: [
    {
      id: 'wavelength',
      question: 'How does the colour of the light change the fringe width?',
      hint: '1. Choose the red laser and press Start. 2. Record the trial. 3. Choose green, then violet, recording each time. 4. Tick two trials to compare β.',
      presetId: 'red',
      review: 'draft',
    },
    {
      id: 'separation',
      question: 'What happens to the fringes when the slits are moved closer together?',
      hint: '1. Record a trial at d = 0.50 mm. 2. Set d to 0.25 mm (half as far apart). 3. Record again and compare β. Keep λ and D the same.',
      review: 'draft',
    },
    {
      id: 'distance',
      question: 'What happens to the fringes when the screen is moved further away?',
      hint: '1. Record a trial at D = 1.50 m. 2. Set D to 3.00 m. 3. Record again and compare β. Keep λ and d the same.',
      review: 'draft',
    },
    {
      id: 'water',
      question: 'Fill the apparatus with water. What happens to the fringes, and by how much?',
      hint: 'Record a trial in air, then choose water and record again. Compare β, and compare the wavelength in the medium.',
      presetId: 'water',
      review: 'draft',
    },
    {
      id: 'unequal',
      question: 'If one slit lets through less light, do the dark fringes stay completely dark?',
      hint: 'Move the detector onto a dark fringe and read the intensity. Then change Slit 2 brightness and watch the reading and the fringe visibility.',
      presetId: 'unequal',
      review: 'draft',
    },
    {
      id: 'detector',
      question: 'What is the path difference at the first dark fringe beside the centre?',
      hint: 'Drag the detector from the centre until it reads "Dark fringe". Compare the path difference with the wavelength.',
      review: 'draft',
    },
  ],
  explanations: [
    {
      id: 'two-sources',
      anchor: { kind: 'simulation' },
      title: 'Two sources, one pattern',
      body: 'Light from the laser reaches both slits at the same moment, so the two slits act as two sources that are always in step (coherent).\n\nAt any point on the screen, the waves from the two slits have travelled different distances. Where the path difference is a whole number of wavelengths (Δ = nλ), crest meets crest and the light is bright. Where it is an odd number of half-wavelengths (Δ = (n + ½)λ), crest meets trough and the light cancels.',
      review: 'draft',
    },
    {
      id: 'key-formula',
      anchor: { kind: 'simulation' },
      title: 'Key formula',
      body: 'Fringe width β = λD/d\n\nBright fringes at y = nλD/d and dark fringes at y = (n + ½)λD/d, where n = 0, ±1, ±2, … The central fringe (n = 0) is bright because the path difference there is zero.\n\nIntensity: I = I₁ + I₂ + 2√(I₁I₂) cos φ, with phase difference φ = 2πΔ/λ. For equal slits, I = 4I₀ cos²(φ/2).',
      review: 'draft',
    },
    {
      id: 'laser',
      anchor: { kind: 'object', id: 'laser' },
      title: 'A coherent source',
      body: 'Interference needs sources with a constant phase difference. A laser gives light of a single wavelength whose waves stay in step, so the light reaching the two slits is coherent. Two separate bulbs would not give a steady pattern.',
      review: 'draft',
    },
    {
      id: 'slits',
      anchor: { kind: 'object', id: 'slits' },
      title: 'The double slit',
      body: 'Each narrow slit spreads the light out, acting as a new source of waves (Huygens’ principle). The two slits S₁ and S₂ are lit by the same wave, so they emit in step.\n\nMoving the slits closer together (smaller d) makes the path difference change more slowly across the screen, so the fringes spread out.',
      review: 'draft',
    },
    {
      id: 'screen',
      anchor: { kind: 'object', id: 'screen' },
      title: 'The fringes on the screen',
      body: 'The screen shows equally spaced bright and dark fringes, with a bright central maximum. The spacing between neighbouring bright fringes is the fringe width β. The ruler below the screen is in millimetres.',
      review: 'draft',
    },
    {
      id: 'detector',
      anchor: { kind: 'object', id: 'detector' },
      title: 'The detector',
      body: 'A small light meter. Drag it along the screen to measure the brightness, the path difference and the phase difference at any point.',
      review: 'draft',
    },
    {
      id: 'wavelength',
      anchor: { kind: 'variable', id: 'wavelength' },
      title: 'Wavelength',
      body: 'A longer wavelength needs a larger path difference to reach the next bright fringe, so the fringes are further apart: β is proportional to λ. Red fringes are wider than violet ones.',
      review: 'draft',
    },
    {
      id: 'separation',
      anchor: { kind: 'variable', id: 'slitSeparation' },
      title: 'Slit separation',
      body: 'The path difference grows faster across the screen when the slits are further apart, so the fringes are closer together: β is inversely proportional to d.',
      review: 'draft',
    },
    {
      id: 'distance',
      anchor: { kind: 'variable', id: 'screenDistance' },
      title: 'Screen distance',
      body: 'The bright and dark directions spread out from the slits like a fan. The further away the screen, the more the fan has spread when it arrives, so β is proportional to D.',
      review: 'draft',
    },
    {
      id: 'medium',
      anchor: { kind: 'variable', id: 'medium' },
      title: 'In water',
      body: 'Light travels more slowly in water, and its wavelength becomes λ/n. With a shorter wavelength the fringes move closer together: β′ = β/n.',
      review: 'draft',
    },
    {
      id: 'slit2',
      anchor: { kind: 'variable', id: 'slit2Intensity' },
      title: 'Unequal slits',
      body: 'If one slit lets through less light, its wave cannot fully cancel the other at the dark fringes, so they are no longer completely dark: I_min = (√I₁ − √I₂)². The fringes are still in the same places.',
      review: 'draft',
    },
    {
      id: 'fringe-width',
      anchor: { kind: 'measurement', id: 'fringeWidth' },
      title: 'Fringe width',
      body: 'β = λD/d is the distance between the centres of neighbouring bright fringes (and also between neighbouring dark fringes).',
      review: 'draft',
    },
    {
      id: 'detector-fringe',
      anchor: { kind: 'measurement', id: 'detectorFringe' },
      title: 'Bright or dark?',
      body: 'At the detector, Δ ÷ λ tells you which: a whole number means bright (constructive), a whole number plus ½ means dark (destructive).',
      review: 'draft',
    },
  ],
  model: {
    kind: 'continuous',
    fixedTimeStep: 1 / 120,
    createInitialState,
    step,
    measure,
    isComplete,
  },
})
