import type { ModelKind } from '@/engine'
import type { DivisionId, LabEntry } from './types'

/** A catalogued lab that is not built yet. `experience` is the planned model kind. */
const planned = (
  division: DivisionId,
  id: string,
  title: string,
  chapter: string,
  experience: ModelKind,
  description?: string,
): LabEntry => ({
  id,
  division,
  title,
  chapter,
  experience,
  status: 'planned',
  ...(description === undefined ? {} : { description }),
})

/**
 * The complete lab catalogue: every lab the platform offers or plans, in
 * display order within each division. Only labs marked `available` can be
 * launched; the rest show the learner what is coming.
 *
 * Planned `experience` values are the intended model kind and may change
 * when a lab is designed.
 */
export const LAB_CATALOGUE: readonly LabEntry[] = [
  // ───────────────────────────── Physics (16) ─────────────────────────────
  {
    id: 'projectile-motion',
    division: 'physics',
    title: 'Projectile Motion',
    chapter: 'Motion in a Plane',
    description: 'Launch a ball and see how speed, angle, height and gravity shape its path.',
    experience: 'continuous',
    status: 'available',
    simulationId: 'projectile-motion',
  },
  planned(
    'physics',
    'matter-waves',
    'Matter Waves',
    'Dual Nature of Radiation and Matter',
    'static',
    "Relate a particle's momentum to its de Broglie wavelength, λ = h/p.",
  ),
  planned(
    'physics',
    'matter-waves-3d',
    'Matter Waves 3D',
    'Dual Nature of Radiation and Matter',
    'static',
    'Visualise matter waves in three dimensions and how their wavelength changes with momentum.',
  ),
  planned(
    'physics',
    'heisenberg-3d',
    'Heisenberg 3D',
    'Atoms & Modern Physics',
    'static',
    'Explore the trade-off between uncertainty in position and in momentum.',
  ),
  planned(
    'physics',
    'blackbody-radiation',
    'Blackbody Radiation',
    'Atoms & Modern Physics',
    'static',
    "See how a hot body's emission spectrum grows and shifts as its temperature rises.",
  ),
  planned(
    'physics',
    'basic-maths-for-physics',
    'Basic Maths for Physics',
    'Mathematical Tools',
    'static',
    'Vectors, components and graphs: the mathematical tools used throughout physics.',
  ),
  planned(
    'physics',
    'electric-flux-cube',
    'Electric Flux — Cube',
    'Electric Charges and Fields',
    'static',
    'Place a charge in or near a cube and measure the electric flux through its faces.',
  ),
  planned(
    'physics',
    'em-wave',
    'EM Wave',
    'Electromagnetic Waves',
    'continuous',
    'Watch perpendicular electric and magnetic fields travel together as a wave.',
  ),
  {
    id: 'collision-1d',
    division: 'physics',
    title: '1D Collision',
    chapter: 'Work, Energy and Power',
    experience: 'continuous',
    status: 'available',
    simulationId: 'collision-1d',
    description: 'Collide two masses on a track and compare momentum and kinetic energy before and after.',
  },
  {
    id: 'double-slit',
    division: 'physics',
    title: 'Double Slit (YDSE)',
    chapter: 'Wave Optics',
    description: 'Change wavelength, slit separation and screen distance to shape an interference pattern.',
    experience: 'continuous',
    status: 'available',
    simulationId: 'double-slit',
  },
  planned(
    'physics',
    'rolling-race',
    'Rolling Race',
    'System of Particles and Rotational Motion',
    'continuous',
    'Race objects down an incline and see how the way their mass is spread affects their speed.',
  ),
  planned(
    'physics',
    'total-internal-reflection',
    'Total Internal Reflection',
    'Ray Optics and Optical Instruments',
    'static',
    'Send light across a boundary and find the critical angle where total internal reflection begins.',
  ),
  planned(
    'physics',
    'loop-solenoid-field',
    'Loop → Solenoid Field',
    'Moving Charges and Magnetism',
    'static',
    'Stack current loops into a solenoid and watch the field inside become uniform.',
  ),
  planned(
    'physics',
    'lenz-law',
    "Lenz's Law",
    'Electromagnetic Induction',
    'continuous',
    'Move a magnet through a coil and see the induced current oppose the change in flux.',
  ),
  planned(
    'physics',
    'escape-velocity',
    'Escape Velocity',
    'Gravitation',
    'continuous',
    "Launch from a planet's surface and find the speed needed to escape its gravity.",
  ),
  planned(
    'physics',
    'pn-junction',
    'p–n Junction & Depletion Layer',
    'Semiconductor Electronics',
    'static',
    'See how a depletion layer forms at a p–n junction and changes under forward and reverse bias.',
  ),

  // ──────────────────────────── Chemistry (30) ────────────────────────────
  planned(
    'chemistry',
    'particle-vs-mole',
    '1 Particle vs 1 Mole',
    'Some Basic Concepts of Chemistry',
    'static',
  ),
  planned('chemistry', 'gram-equivalent', 'Gram Equivalent', 'Stoichiometry & Mole Concept', 'static'),
  planned('chemistry', 'n-factor', 'N-Factor Explorer', 'Stoichiometry & Mole Concept', 'static'),
  planned('chemistry', 'atomic-orbitals', 'Atomic Orbitals', 'Structure of Atom', 'static'),
  planned('chemistry', 'orbital-nodes', 'Orbital Nodes', 'Structure of Atom', 'static'),
  planned('chemistry', 'atomic-mass-unit', 'Atomic Mass Unit', 'Structure of Atom', 'static'),
  planned(
    'chemistry',
    'ionisation-enthalpy',
    'Ionisation Enthalpy',
    'Classification of Elements & Periodicity',
    'static',
  ),
  planned(
    'chemistry',
    'electron-gain-enthalpy',
    'Electron Gain Enthalpy',
    'Classification of Elements & Periodicity',
    'static',
  ),
  planned('chemistry', 'methane', 'Methane', 'Chemical Bonding & Molecular Structure', 'static'),
  planned('chemistry', 'hybridisation', 'Hybridisation', 'Chemical Bonding & Molecular Structure', 'static'),
  planned('chemistry', 'ionic-lattice', 'Ionic Lattice', 'Chemical Bonding & Molecular Structure', 'static'),
  planned(
    'chemistry',
    'valence-bond-theory',
    'Valence Bond Theory',
    'Chemical Bonding & Molecular Structure',
    'static',
  ),
  planned(
    'chemistry',
    'pi-electron-cloud',
    'π Electron Cloud',
    'Chemical Bonding & Molecular Structure',
    'static',
  ),
  planned('chemistry', 'states-of-matter', 'States of Matter', 'States of Matter', 'continuous'),
  planned(
    'chemistry',
    'hydration-enthalpy',
    'Hydration Enthalpy',
    'Thermodynamics & s-Block Elements',
    'static',
  ),
  planned('chemistry', 'dynamic-equilibrium', 'Dynamic Equilibrium', 'Equilibrium', 'continuous'),
  planned('chemistry', 'osmosis', "Osmosis & van't Hoff i", 'Solutions', 'continuous'),
  planned('chemistry', 'galvanic-cell', 'Galvanic Cell', 'Electrochemistry', 'continuous'),
  planned('chemistry', 'collision-theory', 'Collision Theory', 'Chemical Kinetics', 'continuous'),
  planned(
    'chemistry',
    'conformations',
    'Conformations',
    'Organic Chemistry — Some Basic Principles',
    'static',
  ),
  planned(
    'chemistry',
    'symmetry-elements',
    'Symmetry Elements',
    'Organic Chemistry — Some Basic Principles',
    'static',
  ),
  planned('chemistry', 'chirality-3d', 'Chirality 3D', 'Organic Chemistry — Some Basic Principles', 'static'),
  planned('chemistry', 'meso-vs-racemic', 'meso vs (±)', 'Stereochemistry & Isomerism', 'static'),
  planned('chemistry', 'sn2-inversion', 'SN2 Inversion', 'Haloalkanes & Haloarenes', 'discrete'),
  planned('chemistry', 'sn1-racemisation', 'SN1 Racemisation', 'Haloalkanes & Haloarenes', 'discrete'),
  planned('chemistry', 'e2-elimination', 'E2 Elimination', 'Haloalkanes & Haloarenes', 'discrete'),
  planned('chemistry', 'e1-e2-e1cb', 'E1 vs E2 vs E1cb', 'Haloalkanes & Haloarenes', 'discrete'),
  planned(
    'chemistry',
    'carbonyl-addition',
    'Carbonyl Addition',
    'Aldehydes, Ketones & Carboxylic Acids',
    'discrete',
  ),
  planned(
    'chemistry',
    'crystal-field-splitting',
    'Crystal Field Splitting',
    'Coordination Compounds',
    'static',
  ),
  planned('chemistry', 'unit-cell-packing', 'Unit Cell Packing', 'The Solid State', 'static'),

  // ───────────────────────────── Botany (12) ──────────────────────────────
  planned('botany', 'nucleosome', 'Nucleosome', 'Molecular Basis of Inheritance', 'static'),
  planned('botany', 'dna-packaging', 'DNA Packaging', 'Molecular Basis of Inheritance', 'discrete'),
  planned('botany', 'prokaryotic-cell', 'Prokaryotic Cell', 'Cell: The Unit of Life', 'static'),
  planned('botany', 'marchantia', 'Marchantia', 'Plant Kingdom', 'static'),
  planned('botany', 'light-reaction-3d', 'Light Reaction 3D', 'Photosynthesis in Higher Plants', 'discrete'),
  planned('botany', 'kranz-anatomy-c4', 'Kranz Anatomy C4 3D', 'Photosynthesis in Higher Plants', 'static'),
  planned('botany', 'crossing-over', 'Crossing Over', 'Cell Cycle and Cell Division', 'discrete'),
  planned('botany', 'monocot-vs-dicot', 'Monocot vs Dicot Anatomy', 'Anatomy of Flowering Plants', 'static'),
  planned('botany', 'placentation-3d', 'Placentation 3D', 'Morphology of Flowering Plants', 'static'),
  planned(
    'botany',
    'double-fertilisation',
    'Double Fertilisation',
    'Sexual Reproduction in Flowering Plants',
    'discrete',
  ),
  planned(
    'botany',
    'anther-pollen-3d',
    'Anther & Pollen Grain 3D',
    'Sexual Reproduction in Flowering Plants',
    'static',
  ),
  planned('botany', 'transpiration-pull', 'Transpiration Pull', 'Transport in Plants', 'continuous'),

  // ───────────────────────────── Zoology (15) ─────────────────────────────
  planned('zoology', 'mitochondria', 'Mitochondria', 'Cell: The Unit of Life', 'static'),
  planned('zoology', 'cardiac-cycle', 'Cardiac Cycle', 'Circulatory System', 'continuous'),
  planned('zoology', 'synapse-firing', 'Synapse Firing', 'Neural Control and Coordination', 'discrete'),
  planned('zoology', 'human-brain', 'Human Brain', 'Neural Control and Coordination', 'static'),
  planned('zoology', 'cochlea', 'Cochlea: Pitch Is a Place', 'Neural Control and Coordination', 'static'),
  planned('zoology', 'epithelium-types', 'Epithelium Types', 'Structural Organisation in Animals', 'static'),
  planned('zoology', 'frog-anatomy-3d', 'Frog Anatomy 3D', 'Structural Organisation in Animals', 'static'),
  planned(
    'zoology',
    'breathing-mechanism',
    'Breathing Mechanism',
    'Breathing and Exchange of Gases',
    'continuous',
  ),
  planned('zoology', 'sliding-filament', 'Sliding Filament', 'Locomotion and Movement', 'continuous'),
  planned(
    'zoology',
    'nephron-filtration',
    'Nephron Filtration',
    'Excretory Products and their Elimination',
    'continuous',
  ),
  planned('zoology', 'sperm-vs-ovum', '4 Sperm vs 1 Ovum', 'Human Reproduction', 'discrete'),
  planned(
    'zoology',
    'fertilisation-implantation-3d',
    'Fertilisation & Implantation 3D',
    'Human Reproduction',
    'discrete',
  ),
  planned('zoology', 'body-plan-coelom', 'Body Plan & Coelom', 'Animal Kingdom', 'static'),
  planned('zoology', 'villi-absorption-3d', 'Villi Absorption 3D', 'Digestion and Absorption', 'static'),
  planned('zoology', 'antibody-structure-3d', 'Antibody Structure 3D', 'Human Health and Disease', 'static'),
]
