import { defineSimulation } from '@/engine'
import { createInitialState, isRaceOver, laneState, readLane, step, winnerOf, type Lane } from './model'

export const RACE_TIME_STEP = 1 / 240

/** Exported so dragging the start gate uses the slider's limits. */
export const distanceVariable = {
  kind: 'number',
  id: 'distance',
  label: 'Race distance L',
  description: 'How far up the slope the start line is from the finish line. Drag the start gate to move it.',
  unit: 'm',
  defaultValue: 2,
  min: 0.5,
  max: 2.5,
  step: 0.05,
} as const

const shapeOptions = [
  { value: 'solid-sphere', label: 'Solid sphere (I = ⅖mr²)' },
  { value: 'solid-cylinder', label: 'Solid cylinder (I = ½mr²)' },
  { value: 'hollow-sphere', label: 'Hollow sphere (I = ⅔mr²)' },
  { value: 'ring', label: 'Ring (I = mr²)' },
] as const

type Shape = (typeof shapeOptions)[number]['value']

function laneVariables<N extends Lane>(lane: N, shape: Shape) {
  return [
    {
      kind: 'choice',
      id: `shape${lane}`,
      label: `Lane ${lane} body`,
      description: `The body racing in lane ${lane}.`,
      defaultValue: shape,
      options: shapeOptions,
    },
    {
      kind: 'number',
      id: `mass${lane}`,
      label: `Lane ${lane} mass`,
      unit: 'kg',
      defaultValue: 1,
      min: 0.1,
      max: 5,
      step: 0.1,
    },
    {
      kind: 'number',
      id: `radius${lane}`,
      label: `Lane ${lane} radius`,
      unit: 'mm',
      defaultValue: 50,
      min: 20,
      max: 120,
      step: 1,
    },
  ] as const
}

function laneMeasurements<N extends Lane>(lane: N) {
  return [
    { kind: 'scalar', id: `distance${lane}`, label: `Lane ${lane} distance rolled`, unit: 'm' },
    { kind: 'scalar', id: `speed${lane}`, label: `Lane ${lane} speed v`, unit: 'm/s' },
    { kind: 'scalar', id: `acceleration${lane}`, label: `Lane ${lane} acceleration a`, unit: 'm/s²' },
    { kind: 'scalar', id: `angularVelocity${lane}`, label: `Lane ${lane} angular velocity ω`, unit: 'rad/s' },
    {
      kind: 'scalar',
      id: `translationalEnergy${lane}`,
      label: `Lane ${lane} KE of motion (½mv²)`,
      unit: 'J',
    },
    { kind: 'scalar', id: `rotationalEnergy${lane}`, label: `Lane ${lane} KE of spin (½Iω²)`, unit: 'J' },
    { kind: 'scalar', id: `potentialEnergy${lane}`, label: `Lane ${lane} PE above the finish`, unit: 'J' },
    {
      kind: 'scalar',
      id: `momentOfInertia${lane}`,
      label: `Lane ${lane} moment of inertia I`,
      unit: 'kg·m²',
    },
  ] as const
}

export const rollingRace = defineSimulation({
  id: 'rolling-race',
  domain: 'physics',
  title: 'Rolling Race',
  description:
    'Race a sphere, a cylinder and a ring down the same slope, and find out why the way mass is spread decides the winner.',
  learningObjectives: [
    'Use the rolling condition v = ωr and explain why a rolling body has both translational and rotational kinetic energy.',
    'Use a = g sin θ / (1 + I/(mr²)) to predict which body wins a race down an incline.',
    'Explain why the finishing order depends only on the shape — not on mass or radius.',
    'Use energy conservation, mgh = ½mv² + ½Iω², to find the share of energy that goes into spinning.',
  ],
  assumptions: [
    'Uniform bodies of ideal shape: a solid sphere, a solid cylinder, a thin-shelled hollow sphere and a thin ring (the same as a thin-walled hollow cylinder).',
    'Every body rolls without slipping. The rubber lanes have static friction μs = 0.80; the most any body needs in the allowed range is 0.50 (a ring at 45°). Static friction does no work, so mechanical energy is conserved.',
    'No rolling resistance, air drag or bearing losses.',
    'Each body starts at rest with its centre on the start line. Distance and time refer to the centre of mass.',
    'Motion is uniformly accelerated and computed exactly (no numerical approximation).',
    'A foam catcher stops each body just after its centre crosses the finish line. Readings freeze at that moment, like a photogate.',
    'Everything is drawn to true scale.',
  ],
  // Side-on and raised, looking across the three lanes; frames the ramp up to 45°.
  scene: { worldUnit: 'm', camera: { position: [1.2, 3.1, 5.4], target: [1.25, 0.5, 0], fov: 40 } },
  variables: [
    {
      kind: 'number',
      id: 'angle',
      label: 'Incline angle θ',
      description: 'How steep the ramp is.',
      unit: 'deg',
      defaultValue: 10,
      min: 2,
      max: 45,
      step: 0.5,
    },
    distanceVariable,
    {
      kind: 'number',
      id: 'gravity',
      label: 'Gravity g',
      description: 'Earth ≈ 9.81, Moon ≈ 1.62, Jupiter ≈ 24.8.',
      unit: 'm/s²',
      defaultValue: 9.81,
      min: 1.6,
      max: 25,
      step: 0.01,
    },
    ...laneVariables(1, 'solid-sphere'),
    ...laneVariables(2, 'solid-cylinder'),
    ...laneVariables(3, 'ring'),
  ],
  measurements: [
    {
      kind: 'scalar',
      id: 'time1',
      label: 'Lane 1 time',
      description: 'Race time in lane 1. The clock stops when the body crosses the finish line.',
      unit: 's',
      emphasis: 'primary',
    },
    {
      kind: 'scalar',
      id: 'time2',
      label: 'Lane 2 time',
      description: 'Race time in lane 2.',
      unit: 's',
      emphasis: 'primary',
    },
    {
      kind: 'scalar',
      id: 'time3',
      label: 'Lane 3 time',
      description: 'Race time in lane 3.',
      unit: 's',
      emphasis: 'primary',
    },
    {
      kind: 'category',
      id: 'winner',
      label: 'Winner',
      options: [
        { value: 'ready', label: 'Not started' },
        { value: 'racing', label: 'Racing…' },
        { value: 'lane1', label: 'Lane 1' },
        { value: 'lane2', label: 'Lane 2' },
        { value: 'lane3', label: 'Lane 3' },
        { value: 'tie', label: 'Tie' },
      ],
    },
    ...laneMeasurements(1),
    ...laneMeasurements(2),
    ...laneMeasurements(3),
  ],
  objects: [
    { id: 'body1', label: 'Lane 1 body', selectable: true },
    { id: 'body2', label: 'Lane 2 body', selectable: true },
    { id: 'body3', label: 'Lane 3 body', selectable: true },
    { id: 'ramp', label: 'Ramp', selectable: true },
    { id: 'startGate', label: 'Start gate', selectable: true },
  ],
  interactions: [
    { id: 'move-start', kind: 'drag', targetObjectId: 'startGate', variableId: 'distance' },
    { id: 'select-body1', kind: 'select', targetObjectId: 'body1' },
    { id: 'select-body2', kind: 'select', targetObjectId: 'body2' },
    { id: 'select-body3', kind: 'select', targetObjectId: 'body3' },
    { id: 'select-ramp', kind: 'select', targetObjectId: 'ramp' },
  ],
  presets: [
    {
      id: 'shapes',
      title: 'Sphere vs cylinder vs ring',
      variables: {
        shape1: 'solid-sphere',
        shape2: 'solid-cylinder',
        shape3: 'ring',
        mass1: 1,
        mass2: 1,
        mass3: 1,
        radius1: 50,
        radius2: 50,
        radius3: 50,
      },
    },
    {
      id: 'hollow',
      title: 'Solid vs hollow',
      variables: {
        shape1: 'solid-sphere',
        shape2: 'hollow-sphere',
        shape3: 'solid-cylinder',
        mass1: 1,
        mass2: 1,
        mass3: 1,
        radius1: 60,
        radius2: 60,
        radius3: 60,
      },
    },
    {
      id: 'sizes',
      title: 'Big vs small spheres',
      variables: {
        shape1: 'solid-sphere',
        shape2: 'solid-sphere',
        shape3: 'solid-sphere',
        mass1: 1,
        mass2: 1,
        mass3: 1,
        radius1: 30,
        radius2: 60,
        radius3: 100,
      },
    },
    {
      id: 'masses',
      title: 'Heavy vs light rings',
      variables: {
        shape1: 'ring',
        shape2: 'ring',
        shape3: 'ring',
        mass1: 0.2,
        mass2: 1,
        mass3: 5,
        radius1: 60,
        radius2: 60,
        radius3: 60,
      },
    },
    { id: 'steep', title: 'Steep (30°)', variables: { angle: 30 } },
    { id: 'moon', title: 'On the Moon', variables: { gravity: 1.62 } },
    { id: 'short', title: 'Short race (0.5 m)', variables: { distance: 0.5 } },
  ],
  investigations: [
    {
      id: 'shapes',
      question: 'A sphere, a cylinder and a ring race. Which wins?',
      hint: 'Predict the order first, then start the race. All three have the same mass and radius.',
      presetId: 'shapes',
      review: 'draft',
    },
    {
      id: 'radius',
      question: 'Does a bigger sphere roll down faster?',
      hint: 'Race three solid spheres of different sizes and compare their times.',
      presetId: 'sizes',
      review: 'draft',
    },
    {
      id: 'mass',
      question: 'Does a heavier ring win?',
      hint: 'Race rings of 0.2 kg, 1 kg and 5 kg. Record the trial and look at the times.',
      presetId: 'masses',
      review: 'draft',
    },
    {
      id: 'angle',
      question: 'Does a steeper ramp change who wins?',
      hint: 'Record the race at 10°, then at 30°. Compare the times and the order.',
      review: 'draft',
    },
    {
      id: 'energy',
      question: 'Where does the energy go?',
      hint: 'Switch on "Energy columns" in the legend, then race. Compare how much of each body’s energy goes into spinning.',
      review: 'draft',
    },
    {
      id: 'acceleration',
      question: 'Measure the acceleration from the race time.',
      hint: 'Use a = 2L/t² with the distance and a lane time, then compare with g sin θ / (1 + k) and the measured value in More details.',
      review: 'draft',
    },
  ],
  explanations: [
    {
      id: 'overview',
      anchor: { kind: 'simulation' },
      title: 'Why the shapes don’t tie',
      body: 'All three bodies lose the same fraction of their potential energy per metre. But a rolling body has to spend some of that energy on spinning, and only the rest makes it move forward.\n\nThe further the mass sits from the axle, the more energy the spinning takes. A ring has all its mass at the rim, so half its energy goes into spin and it is slowest. A solid sphere keeps most of its mass near the centre, so it wins.',
      review: 'draft',
    },
    {
      id: 'key-formula',
      anchor: { kind: 'simulation' },
      title: 'Key formula',
      body: 'Rolling without slipping: v = ωr.\n\nMoment of inertia: I = k m r². Solid sphere k = ⅖, solid cylinder k = ½, hollow sphere k = ⅔, ring k = 1.\n\nEnergy: mgh = ½mv² + ½Iω² = ½mv²(1 + k).\n\nAcceleration down the slope: a = g sin θ / (1 + k). Race time: t = √(2L/a).\n\nMass m and radius r cancel: only k decides the race.',
      review: 'draft',
    },
    {
      id: 'body',
      anchor: { kind: 'object', id: 'body1' },
      title: 'Mass distribution',
      body: 'The painted band turns as the body rolls: it turns once for every 2πr the body moves (v = ωr). Solid bodies keep much of their mass near the axle; hollow ones and rings keep it at the outside, which makes them harder to spin up.',
      review: 'draft',
    },
    {
      id: 'body2',
      anchor: { kind: 'object', id: 'body2' },
      title: 'Mass distribution',
      body: 'Compare the moments of inertia in More details. For the same mass and radius, a larger I means more energy goes into spinning, so the body moves forward more slowly.',
      review: 'draft',
    },
    {
      id: 'body3',
      anchor: { kind: 'object', id: 'body3' },
      title: 'Mass distribution',
      body: 'A ring (or thin-walled hollow cylinder) has all its mass at distance r from the axle, so I = mr². Its spinning energy always equals its forward-motion energy.',
      review: 'draft',
    },
    {
      id: 'ramp',
      anchor: { kind: 'object', id: 'ramp' },
      title: 'The ramp',
      body: 'The rubber lanes grip the bodies so they roll without slipping. Friction at the contact point does no work, because the point touching the ramp is momentarily at rest — so no energy is lost to it.\n\nThe gravity component along the slope, g sin θ, drives every body; friction then turns part of the motion into spin.',
      review: 'draft',
    },
    {
      id: 'start-gate',
      anchor: { kind: 'object', id: 'startGate' },
      title: 'Start gate',
      body: 'The gate releases all three bodies at the same instant from the same line. Drag it up or down the slope to change the race distance.',
      review: 'draft',
    },
    {
      id: 'shape',
      anchor: { kind: 'variable', id: 'shape1' },
      title: 'Moment of inertia',
      body: 'I = k m r² measures how hard a body is to spin up. k depends only on how the mass is spread: ⅖ for a solid sphere, ½ for a solid cylinder, ⅔ for a hollow sphere and 1 for a ring.',
      review: 'draft',
    },
    {
      id: 'mass',
      anchor: { kind: 'variable', id: 'mass1' },
      title: 'Does mass matter?',
      body: 'No. A heavier body has more weight pulling it down the slope, but it is also harder to speed up and harder to spin — by exactly the same factor. Race three rings of different mass to check.',
      review: 'draft',
    },
    {
      id: 'radius',
      anchor: { kind: 'variable', id: 'radius1' },
      title: 'Does radius matter?',
      body: 'No. A bigger body has a larger moment of inertia, but it also needs to turn more slowly for the same speed (ω = v/r). The two effects cancel exactly.',
      review: 'draft',
    },
    {
      id: 'angle',
      anchor: { kind: 'variable', id: 'angle' },
      title: 'Incline angle',
      body: 'A steeper ramp makes every body accelerate faster (a ∝ sin θ), but the finishing order never changes: the ratio of times depends only on the shapes.\n\nOn very steep ramps a real ring may start to slip. Here the lanes grip well enough up to 45°.',
      review: 'draft',
    },
    {
      id: 'time',
      anchor: { kind: 'measurement', id: 'time1' },
      title: 'Race time',
      body: 'From rest with constant acceleration, L = ½at², so t = √(2L/a). The ring’s time is always √(2/1.4) ≈ 1.20 times the solid sphere’s, on any slope and on any planet.',
      review: 'draft',
    },
    {
      id: 'spin-energy',
      anchor: { kind: 'measurement', id: 'rotationalEnergy1' },
      title: 'Energy of spinning',
      body: '½Iω² with ω = v/r gives ½kmv²: the spinning energy is k times the forward-motion energy. Sphere 29 %, cylinder 33 %, hollow sphere 40 %, ring 50 % of the kinetic energy.',
      review: 'draft',
    },
    {
      id: 'angular-velocity',
      anchor: { kind: 'measurement', id: 'angularVelocity1' },
      title: 'Angular velocity',
      body: 'ω = v/r. At the same speed a small body spins much faster than a big one — which is why radius does not change the race.',
      review: 'draft',
    },
  ],
  model: {
    kind: 'continuous',
    fixedTimeStep: RACE_TIME_STEP,
    // Slowest race in range: ring, 2°, g = 1.6, 2.5 m → 13.4 s.
    maxDuration: 60,
    createInitialState,
    step,
    measure: (state, vars) => {
      const r1 = readLane(state, vars, 1)
      const r2 = readLane(state, vars, 2)
      const r3 = readLane(state, vars, 3)
      return {
        time1: laneState(state, 1).time,
        time2: laneState(state, 2).time,
        time3: laneState(state, 3).time,
        winner: winnerOf(state, vars),
        distance1: r1.distance,
        speed1: r1.speed,
        acceleration1: r1.acceleration,
        angularVelocity1: r1.angularVelocity,
        translationalEnergy1: r1.translationalEnergy,
        rotationalEnergy1: r1.rotationalEnergy,
        potentialEnergy1: r1.potentialEnergy,
        momentOfInertia1: r1.momentOfInertia,
        distance2: r2.distance,
        speed2: r2.speed,
        acceleration2: r2.acceleration,
        angularVelocity2: r2.angularVelocity,
        translationalEnergy2: r2.translationalEnergy,
        rotationalEnergy2: r2.rotationalEnergy,
        potentialEnergy2: r2.potentialEnergy,
        momentOfInertia2: r2.momentOfInertia,
        distance3: r3.distance,
        speed3: r3.speed,
        acceleration3: r3.acceleration,
        angularVelocity3: r3.angularVelocity,
        translationalEnergy3: r3.translationalEnergy,
        rotationalEnergy3: r3.rotationalEnergy,
        potentialEnergy3: r3.potentialEnergy,
        momentOfInertia3: r3.momentOfInertia,
      }
    },
    isComplete: isRaceOver,
  },
})
